// AUTO-GENERATED by packages/db/scripts/gen-types.sh — DO NOT EDIT BY HAND.
// Regenerate with `pnpm db:gen`. The CI drift gate fails if this is stale.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      activities: {
        Row: {
          board_slug: string | null
          candidacy_id: string | null
          company_id: string | null
          created_at: string
          detail: Json | null
          error: string | null
          finished_at: string | null
          id: string
          posting_id: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["activity_status"]
          type: Database["public"]["Enums"]["activity_type"]
          updated_at: string
          user_id: string | null
        }
        Insert: {
          board_slug?: string | null
          candidacy_id?: string | null
          company_id?: string | null
          created_at?: string
          detail?: Json | null
          error?: string | null
          finished_at?: string | null
          id?: string
          posting_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["activity_status"]
          type: Database["public"]["Enums"]["activity_type"]
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          board_slug?: string | null
          candidacy_id?: string | null
          company_id?: string | null
          created_at?: string
          detail?: Json | null
          error?: string | null
          finished_at?: string | null
          id?: string
          posting_id?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["activity_status"]
          type?: Database["public"]["Enums"]["activity_type"]
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "activities_board_slug_fkey"
            columns: ["board_slug"]
            isOneToOne: false
            referencedRelation: "boards"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "activities_candidacy_id_fkey"
            columns: ["candidacy_id"]
            isOneToOne: false
            referencedRelation: "candidacies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activities_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activities_posting_id_fkey"
            columns: ["posting_id"]
            isOneToOne: false
            referencedRelation: "postings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activities_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      boards: {
        Row: {
          apply_status: Database["public"]["Enums"]["integration_status"]
          base_url: string
          collect_status: Database["public"]["Enums"]["integration_status"]
          country: string
          created_at: string
          cred_env_prefix: string
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          apply_status?: Database["public"]["Enums"]["integration_status"]
          base_url: string
          collect_status?: Database["public"]["Enums"]["integration_status"]
          country?: string
          created_at?: string
          cred_env_prefix: string
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          apply_status?: Database["public"]["Enums"]["integration_status"]
          base_url?: string
          collect_status?: Database["public"]["Enums"]["integration_status"]
          country?: string
          created_at?: string
          cred_env_prefix?: string
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      candidacies: {
        Row: {
          created_at: string
          id: string
          match_score: number | null
          posting_id: string
          status: Database["public"]["Enums"]["candidacy_status"]
          status_changed_at: string
          triage_decision: Database["public"]["Enums"]["triage_decision"] | null
          triage_reason: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          match_score?: number | null
          posting_id: string
          status?: Database["public"]["Enums"]["candidacy_status"]
          status_changed_at?: string
          triage_decision?:
            | Database["public"]["Enums"]["triage_decision"]
            | null
          triage_reason?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          match_score?: number | null
          posting_id?: string
          status?: Database["public"]["Enums"]["candidacy_status"]
          status_changed_at?: string
          triage_decision?:
            | Database["public"]["Enums"]["triage_decision"]
            | null
          triage_reason?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "candidacies_posting_id_fkey"
            columns: ["posting_id"]
            isOneToOne: false
            referencedRelation: "postings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidacies_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          created_at: string
          description: string | null
          domain: string | null
          enrichment: Json | null
          id: string
          linkedin_url: string | null
          name: string
          normalized_name: string | null
          recruitment_email: string | null
          status: Database["public"]["Enums"]["company_status"]
          updated_at: string
          website_url: string | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          domain?: string | null
          enrichment?: Json | null
          id?: string
          linkedin_url?: string | null
          name: string
          normalized_name?: string | null
          recruitment_email?: string | null
          status?: Database["public"]["Enums"]["company_status"]
          updated_at?: string
          website_url?: string | null
        }
        Update: {
          created_at?: string
          description?: string | null
          domain?: string | null
          enrichment?: Json | null
          id?: string
          linkedin_url?: string | null
          name?: string
          normalized_name?: string | null
          recruitment_email?: string | null
          status?: Database["public"]["Enums"]["company_status"]
          updated_at?: string
          website_url?: string | null
        }
        Relationships: []
      }
      contacts: {
        Row: {
          company_id: string
          created_at: string
          email: string | null
          full_name: string
          id: string
          linkedin_url: string | null
          notes: string | null
          role_title: string | null
          updated_at: string
        }
        Insert: {
          company_id: string
          created_at?: string
          email?: string | null
          full_name: string
          id?: string
          linkedin_url?: string | null
          notes?: string | null
          role_title?: string | null
          updated_at?: string
        }
        Update: {
          company_id?: string
          created_at?: string
          email?: string | null
          full_name?: string
          id?: string
          linkedin_url?: string | null
          notes?: string | null
          role_title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contacts_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          created_at: string
          data: Json | null
          id: string
          run_id: string
          seq: number
          thread_id: string
          type: Database["public"]["Enums"]["event_type"]
        }
        Insert: {
          created_at?: string
          data?: Json | null
          id?: string
          run_id: string
          seq: number
          thread_id: string
          type: Database["public"]["Enums"]["event_type"]
        }
        Update: {
          created_at?: string
          data?: Json | null
          id?: string
          run_id?: string
          seq?: number
          thread_id?: string
          type?: Database["public"]["Enums"]["event_type"]
        }
        Relationships: [
          {
            foreignKeyName: "events_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "events_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "threads"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          content: string | null
          created_at: string
          id: string
          name: string | null
          role: Database["public"]["Enums"]["message_role"]
          run_id: string | null
          thread_id: string
          tool_call_id: string | null
          tool_calls: Json | null
          updated_at: string
        }
        Insert: {
          content?: string | null
          created_at?: string
          id?: string
          name?: string | null
          role: Database["public"]["Enums"]["message_role"]
          run_id?: string | null
          thread_id: string
          tool_call_id?: string | null
          tool_calls?: Json | null
          updated_at?: string
        }
        Update: {
          content?: string | null
          created_at?: string
          id?: string
          name?: string | null
          role?: Database["public"]["Enums"]["message_role"]
          run_id?: string | null
          thread_id?: string
          tool_call_id?: string | null
          tool_calls?: Json | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "threads"
            referencedColumns: ["id"]
          },
        ]
      }
      negative_criteria: {
        Row: {
          created_at: string
          id: string
          text: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          text: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          text?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "negative_criteria_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          kind: string
          read_at: string | null
          ref: Json | null
          title: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          kind?: string
          read_at?: string | null
          ref?: Json | null
          title: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          kind?: string
          read_at?: string | null
          ref?: Json | null
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      postings: {
        Row: {
          board_slug: string
          collected_at: string
          company_id: string | null
          company_name_raw: string | null
          content_hash: string | null
          created_at: string
          description: string | null
          external_id: string | null
          id: string
          location: string | null
          posted_on: string | null
          salary_raw: string | null
          title: string
          updated_at: string
          url: string
          work_mode: Database["public"]["Enums"]["work_mode"]
        }
        Insert: {
          board_slug: string
          collected_at?: string
          company_id?: string | null
          company_name_raw?: string | null
          content_hash?: string | null
          created_at?: string
          description?: string | null
          external_id?: string | null
          id?: string
          location?: string | null
          posted_on?: string | null
          salary_raw?: string | null
          title: string
          updated_at?: string
          url: string
          work_mode?: Database["public"]["Enums"]["work_mode"]
        }
        Update: {
          board_slug?: string
          collected_at?: string
          company_id?: string | null
          company_name_raw?: string | null
          content_hash?: string | null
          created_at?: string
          description?: string | null
          external_id?: string | null
          id?: string
          location?: string | null
          posted_on?: string | null
          salary_raw?: string | null
          title?: string
          updated_at?: string
          url?: string
          work_mode?: Database["public"]["Enums"]["work_mode"]
        }
        Relationships: [
          {
            foreignKeyName: "postings_board_slug_fkey"
            columns: ["board_slug"]
            isOneToOne: false
            referencedRelation: "boards"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "postings_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          about: string | null
          created_at: string
          current_salary: string | null
          linkedin_url: string | null
          location: string | null
          notice_period: string | null
          portfolio_url: string | null
          preferred_salary: string | null
          resume_text: string | null
          resume_url: string | null
          updated_at: string
          user_id: string
          willing_remote: boolean
          work_pref: Database["public"]["Enums"]["work_mode"]
          years_experience: number | null
        }
        Insert: {
          about?: string | null
          created_at?: string
          current_salary?: string | null
          linkedin_url?: string | null
          location?: string | null
          notice_period?: string | null
          portfolio_url?: string | null
          preferred_salary?: string | null
          resume_text?: string | null
          resume_url?: string | null
          updated_at?: string
          user_id: string
          willing_remote?: boolean
          work_pref?: Database["public"]["Enums"]["work_mode"]
          years_experience?: number | null
        }
        Update: {
          about?: string | null
          created_at?: string
          current_salary?: string | null
          linkedin_url?: string | null
          location?: string | null
          notice_period?: string | null
          portfolio_url?: string | null
          preferred_salary?: string | null
          resume_text?: string | null
          resume_url?: string | null
          updated_at?: string
          user_id?: string
          willing_remote?: boolean
          work_pref?: Database["public"]["Enums"]["work_mode"]
          years_experience?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      proposals: {
        Row: {
          board_slug: string | null
          candidacy_id: string | null
          created_at: string
          created_by: string | null
          decided_at: string | null
          decision_note: string | null
          id: string
          kind: string | null
          plan: Json | null
          rationale: string | null
          status: Database["public"]["Enums"]["proposal_status"]
          title: string
          updated_at: string
        }
        Insert: {
          board_slug?: string | null
          candidacy_id?: string | null
          created_at?: string
          created_by?: string | null
          decided_at?: string | null
          decision_note?: string | null
          id?: string
          kind?: string | null
          plan?: Json | null
          rationale?: string | null
          status?: Database["public"]["Enums"]["proposal_status"]
          title: string
          updated_at?: string
        }
        Update: {
          board_slug?: string | null
          candidacy_id?: string | null
          created_at?: string
          created_by?: string | null
          decided_at?: string | null
          decision_note?: string | null
          id?: string
          kind?: string | null
          plan?: Json | null
          rationale?: string | null
          status?: Database["public"]["Enums"]["proposal_status"]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "proposals_board_slug_fkey"
            columns: ["board_slug"]
            isOneToOne: false
            referencedRelation: "boards"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "proposals_candidacy_id_fkey"
            columns: ["candidacy_id"]
            isOneToOne: false
            referencedRelation: "candidacies"
            referencedColumns: ["id"]
          },
        ]
      }
      runs: {
        Row: {
          created_at: string
          error: string | null
          finished_at: string | null
          id: string
          input: Json | null
          outcome: Json | null
          parent_run_id: string | null
          started_at: string
          status: Database["public"]["Enums"]["run_status"]
          thread_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          outcome?: Json | null
          parent_run_id?: string | null
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
          thread_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          outcome?: Json | null
          parent_run_id?: string | null
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
          thread_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "runs_parent_run_id_fkey"
            columns: ["parent_run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "runs_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: false
            referencedRelation: "threads"
            referencedColumns: ["id"]
          },
        ]
      }
      target_titles: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          title: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          title: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "target_titles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      thread_state: {
        Row: {
          created_at: string
          state: Json
          thread_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          state?: Json
          thread_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          state?: Json
          thread_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "thread_state_thread_id_fkey"
            columns: ["thread_id"]
            isOneToOne: true
            referencedRelation: "threads"
            referencedColumns: ["id"]
          },
        ]
      }
      threads: {
        Row: {
          created_at: string
          id: string
          title: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          title?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          title?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "threads_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          email: string | null
          full_name: string | null
          id: string
        }
        Insert: {
          avatar_url?: string | null
          email?: string | null
          full_name?: string | null
          id: string
        }
        Update: {
          avatar_url?: string | null
          email?: string | null
          full_name?: string | null
          id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      activity_status: "queued" | "in_progress" | "succeeded" | "failed"
      activity_type:
        | "collect"
        | "match"
        | "enrich"
        | "cover_letter"
        | "apply"
        | "external_fill"
        | "proposal_exec"
        | "cli_repair"
        | "deploy"
      candidacy_status:
        | "new"
        | "dismissed"
        | "shortlisted"
        | "alternative_outreach"
        | "awaiting_cover_letter"
        | "drafting"
        | "in_review"
        | "approved"
        | "applying"
        | "applied"
        | "external_pending"
        | "application_failed"
      company_status: "new" | "researching" | "enriched" | "enrichment_failed"
      event_type:
        | "run_started"
        | "run_finished"
        | "run_error"
        | "step_started"
        | "step_finished"
        | "text_message_start"
        | "text_message_content"
        | "text_message_end"
        | "text_message_chunk"
        | "tool_call_start"
        | "tool_call_args"
        | "tool_call_end"
        | "tool_call_chunk"
        | "tool_call_result"
        | "state_snapshot"
        | "state_delta"
        | "messages_snapshot"
        | "activity_snapshot"
        | "activity_delta"
        | "reasoning_start"
        | "reasoning_message"
        | "reasoning_end"
        | "raw"
        | "custom"
      integration_status:
        | "not_integrated"
        | "in_progress"
        | "integrated"
        | "broken"
      message_role:
        | "user"
        | "assistant"
        | "system"
        | "developer"
        | "tool"
        | "reasoning"
        | "activity"
      proposal_status:
        | "submitted"
        | "approved"
        | "rejected"
        | "in_progress"
        | "completed"
        | "failed"
      run_status: "running" | "completed" | "interrupted" | "error"
      triage_decision: "shortlisted" | "alternative_outreach" | "dismissed"
      work_mode: "remote" | "hybrid" | "office" | "unknown"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      activity_status: ["queued", "in_progress", "succeeded", "failed"],
      activity_type: [
        "collect",
        "match",
        "enrich",
        "cover_letter",
        "apply",
        "external_fill",
        "proposal_exec",
        "cli_repair",
        "deploy",
      ],
      candidacy_status: [
        "new",
        "dismissed",
        "shortlisted",
        "alternative_outreach",
        "awaiting_cover_letter",
        "drafting",
        "in_review",
        "approved",
        "applying",
        "applied",
        "external_pending",
        "application_failed",
      ],
      company_status: ["new", "researching", "enriched", "enrichment_failed"],
      event_type: [
        "run_started",
        "run_finished",
        "run_error",
        "step_started",
        "step_finished",
        "text_message_start",
        "text_message_content",
        "text_message_end",
        "text_message_chunk",
        "tool_call_start",
        "tool_call_args",
        "tool_call_end",
        "tool_call_chunk",
        "tool_call_result",
        "state_snapshot",
        "state_delta",
        "messages_snapshot",
        "activity_snapshot",
        "activity_delta",
        "reasoning_start",
        "reasoning_message",
        "reasoning_end",
        "raw",
        "custom",
      ],
      integration_status: [
        "not_integrated",
        "in_progress",
        "integrated",
        "broken",
      ],
      message_role: [
        "user",
        "assistant",
        "system",
        "developer",
        "tool",
        "reasoning",
        "activity",
      ],
      proposal_status: [
        "submitted",
        "approved",
        "rejected",
        "in_progress",
        "completed",
        "failed",
      ],
      run_status: ["running", "completed", "interrupted", "error"],
      triage_decision: ["shortlisted", "alternative_outreach", "dismissed"],
      work_mode: ["remote", "hybrid", "office", "unknown"],
    },
  },
} as const
