/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as JobsRouteRouteImport } from './routes/jobs/route'
import { Route as CoverLettersRouteRouteImport } from './routes/cover-letters/route'
import { Route as CompaniesRouteRouteImport } from './routes/companies/route'
import { Route as ApplicationsRouteRouteImport } from './routes/applications/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CoverLettersIndexRouteImport } from './routes/cover-letters/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as OnboardingReviewRouteImport } from './routes/onboarding/review'
import { Route as OnboardingResumeRouteImport } from './routes/onboarding/resume'
import { Route as OnboardingIntroRouteImport } from './routes/onboarding/intro'
import { Route as OnboardingHomeRouteImport } from './routes/onboarding/home'
import { Route as OnboardingCriteriaRouteImport } from './routes/onboarding/criteria'
import { Route as OnboardingConversationRouteImport } from './routes/onboarding/conversation'
import { Route as JobsCandidacyIdRouteImport } from './routes/jobs/$candidacyId'
import { Route as CoverLettersCandidacyIdRouteImport } from './routes/cover-letters/$candidacyId'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRouteRoute = JobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLettersRouteRoute = CoverLettersRouteRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRouteRoute = CompaniesRouteRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRouteRoute = ApplicationsRouteRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRouteRoute,
} as any)
const CoverLettersIndexRoute = CoverLettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoverLettersRouteRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRouteRoute,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicationsRouteRoute,
} as any)
const OnboardingReviewRoute = OnboardingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingResumeRoute = OnboardingResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingIntroRoute = OnboardingIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingHomeRoute = OnboardingHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCriteriaRoute = OnboardingCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingConversationRoute = OnboardingConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const JobsCandidacyIdRoute = JobsCandidacyIdRouteImport.update({
  id: '/$candidacyId',
  path: '/$candidacyId',
  getParentRoute: () => JobsRouteRoute,
} as any)
const CoverLettersCandidacyIdRoute = CoverLettersCandidacyIdRouteImport.update({
  id: '/$candidacyId',
  path: '/$candidacyId',
  getParentRoute: () => CoverLettersRouteRoute,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteRouteWithChildren
  '/companies': typeof CompaniesRouteRouteWithChildren
  '/cover-letters': typeof CoverLettersRouteRouteWithChildren
  '/jobs': typeof JobsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/cover-letters/$candidacyId': typeof CoverLettersCandidacyIdRoute
  '/jobs/$candidacyId': typeof JobsCandidacyIdRoute
  '/onboarding/conversation': typeof OnboardingConversationRoute
  '/onboarding/criteria': typeof OnboardingCriteriaRoute
  '/onboarding/home': typeof OnboardingHomeRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/resume': typeof OnboardingResumeRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/cover-letters/': typeof CoverLettersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/cover-letters/$candidacyId': typeof CoverLettersCandidacyIdRoute
  '/jobs/$candidacyId': typeof JobsCandidacyIdRoute
  '/onboarding/conversation': typeof OnboardingConversationRoute
  '/onboarding/criteria': typeof OnboardingCriteriaRoute
  '/onboarding/home': typeof OnboardingHomeRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/resume': typeof OnboardingResumeRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/applications': typeof ApplicationsIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/cover-letters': typeof CoverLettersIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRouteRouteWithChildren
  '/companies': typeof CompaniesRouteRouteWithChildren
  '/cover-letters': typeof CoverLettersRouteRouteWithChildren
  '/jobs': typeof JobsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/cover-letters/$candidacyId': typeof CoverLettersCandidacyIdRoute
  '/jobs/$candidacyId': typeof JobsCandidacyIdRoute
  '/onboarding/conversation': typeof OnboardingConversationRoute
  '/onboarding/criteria': typeof OnboardingCriteriaRoute
  '/onboarding/home': typeof OnboardingHomeRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/resume': typeof OnboardingResumeRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/cover-letters/': typeof CoverLettersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/companies'
    | '/cover-letters'
    | '/jobs'
    | '/onboarding'
    | '/profile'
    | '/auth'
    | '/companies/$companyId'
    | '/cover-letters/$candidacyId'
    | '/jobs/$candidacyId'
    | '/onboarding/conversation'
    | '/onboarding/criteria'
    | '/onboarding/home'
    | '/onboarding/intro'
    | '/onboarding/resume'
    | '/onboarding/review'
    | '/applications/'
    | '/companies/'
    | '/cover-letters/'
    | '/jobs/'
    | '/onboarding/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/companies/$companyId'
    | '/cover-letters/$candidacyId'
    | '/jobs/$candidacyId'
    | '/onboarding/conversation'
    | '/onboarding/criteria'
    | '/onboarding/home'
    | '/onboarding/intro'
    | '/onboarding/resume'
    | '/onboarding/review'
    | '/applications'
    | '/companies'
    | '/cover-letters'
    | '/jobs'
    | '/onboarding'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/companies'
    | '/cover-letters'
    | '/jobs'
    | '/onboarding'
    | '/profile'
    | '/auth'
    | '/companies/$companyId'
    | '/cover-letters/$candidacyId'
    | '/jobs/$candidacyId'
    | '/onboarding/conversation'
    | '/onboarding/criteria'
    | '/onboarding/home'
    | '/onboarding/intro'
    | '/onboarding/resume'
    | '/onboarding/review'
    | '/applications/'
    | '/companies/'
    | '/cover-letters/'
    | '/jobs/'
    | '/onboarding/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRouteRoute: typeof ApplicationsRouteRouteWithChildren
  CompaniesRouteRoute: typeof CompaniesRouteRouteWithChildren
  CoverLettersRouteRoute: typeof CoverLettersRouteRouteWithChildren
  JobsRouteRoute: typeof JobsRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letters': {
      id: '/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof CoverLettersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/cover-letters/': {
      id: '/cover-letters/'
      path: '/'
      fullPath: '/cover-letters/'
      preLoaderRoute: typeof CoverLettersIndexRouteImport
      parentRoute: typeof CoverLettersRouteRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRouteRoute
    }
    '/applications/': {
      id: '/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof ApplicationsRouteRoute
    }
    '/onboarding/review': {
      id: '/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof OnboardingReviewRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/resume': {
      id: '/onboarding/resume'
      path: '/resume'
      fullPath: '/onboarding/resume'
      preLoaderRoute: typeof OnboardingResumeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/intro': {
      id: '/onboarding/intro'
      path: '/intro'
      fullPath: '/onboarding/intro'
      preLoaderRoute: typeof OnboardingIntroRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/home': {
      id: '/onboarding/home'
      path: '/home'
      fullPath: '/onboarding/home'
      preLoaderRoute: typeof OnboardingHomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/criteria': {
      id: '/onboarding/criteria'
      path: '/criteria'
      fullPath: '/onboarding/criteria'
      preLoaderRoute: typeof OnboardingCriteriaRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/conversation': {
      id: '/onboarding/conversation'
      path: '/conversation'
      fullPath: '/onboarding/conversation'
      preLoaderRoute: typeof OnboardingConversationRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/jobs/$candidacyId': {
      id: '/jobs/$candidacyId'
      path: '/$candidacyId'
      fullPath: '/jobs/$candidacyId'
      preLoaderRoute: typeof JobsCandidacyIdRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/cover-letters/$candidacyId': {
      id: '/cover-letters/$candidacyId'
      path: '/$candidacyId'
      fullPath: '/cover-letters/$candidacyId'
      preLoaderRoute: typeof CoverLettersCandidacyIdRouteImport
      parentRoute: typeof CoverLettersRouteRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRouteRoute
    }
  }
}

interface ApplicationsRouteRouteChildren {
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

const ApplicationsRouteRouteChildren: ApplicationsRouteRouteChildren = {
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}

const ApplicationsRouteRouteWithChildren =
  ApplicationsRouteRoute._addFileChildren(ApplicationsRouteRouteChildren)

interface CompaniesRouteRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteRouteChildren: CompaniesRouteRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteRouteWithChildren = CompaniesRouteRoute._addFileChildren(
  CompaniesRouteRouteChildren,
)

interface CoverLettersRouteRouteChildren {
  CoverLettersCandidacyIdRoute: typeof CoverLettersCandidacyIdRoute
  CoverLettersIndexRoute: typeof CoverLettersIndexRoute
}

const CoverLettersRouteRouteChildren: CoverLettersRouteRouteChildren = {
  CoverLettersCandidacyIdRoute: CoverLettersCandidacyIdRoute,
  CoverLettersIndexRoute: CoverLettersIndexRoute,
}

const CoverLettersRouteRouteWithChildren =
  CoverLettersRouteRoute._addFileChildren(CoverLettersRouteRouteChildren)

interface JobsRouteRouteChildren {
  JobsCandidacyIdRoute: typeof JobsCandidacyIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteRouteChildren: JobsRouteRouteChildren = {
  JobsCandidacyIdRoute: JobsCandidacyIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteRouteWithChildren = JobsRouteRoute._addFileChildren(
  JobsRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingConversationRoute: typeof OnboardingConversationRoute
  OnboardingCriteriaRoute: typeof OnboardingCriteriaRoute
  OnboardingHomeRoute: typeof OnboardingHomeRoute
  OnboardingIntroRoute: typeof OnboardingIntroRoute
  OnboardingResumeRoute: typeof OnboardingResumeRoute
  OnboardingReviewRoute: typeof OnboardingReviewRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingConversationRoute: OnboardingConversationRoute,
  OnboardingCriteriaRoute: OnboardingCriteriaRoute,
  OnboardingHomeRoute: OnboardingHomeRoute,
  OnboardingIntroRoute: OnboardingIntroRoute,
  OnboardingResumeRoute: OnboardingResumeRoute,
  OnboardingReviewRoute: OnboardingReviewRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRouteRoute: ApplicationsRouteRouteWithChildren,
  CompaniesRouteRoute: CompaniesRouteRouteWithChildren,
  CoverLettersRouteRoute: CoverLettersRouteRouteWithChildren,
  JobsRouteRoute: JobsRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
