/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as JobsRouteRouteImport } from './routes/jobs/route'
import { Route as CoverLettersRouteRouteImport } from './routes/cover-letters/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CoverLettersIndexRouteImport } from './routes/cover-letters/index'
import { Route as OnboardingReviewRouteImport } from './routes/onboarding/review'
import { Route as OnboardingResumeRouteImport } from './routes/onboarding/resume'
import { Route as OnboardingIntroRouteImport } from './routes/onboarding/intro'
import { Route as OnboardingHomeRouteImport } from './routes/onboarding/home'
import { Route as OnboardingCriteriaRouteImport } from './routes/onboarding/criteria'
import { Route as OnboardingConversationRouteImport } from './routes/onboarding/conversation'
import { Route as JobsCandidacyIdRouteImport } from './routes/jobs/$candidacyId'
import { Route as CoverLettersCandidacyIdRouteImport } from './routes/cover-letters/$candidacyId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRouteRoute = JobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLettersRouteRoute = CoverLettersRouteRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRouteRoute,
} as any)
const CoverLettersIndexRoute = CoverLettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoverLettersRouteRoute,
} as any)
const OnboardingReviewRoute = OnboardingReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingResumeRoute = OnboardingResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingIntroRoute = OnboardingIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingHomeRoute = OnboardingHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCriteriaRoute = OnboardingCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingConversationRoute = OnboardingConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const JobsCandidacyIdRoute = JobsCandidacyIdRouteImport.update({
  id: '/$candidacyId',
  path: '/$candidacyId',
  getParentRoute: () => JobsRouteRoute,
} as any)
const CoverLettersCandidacyIdRoute = CoverLettersCandidacyIdRouteImport.update({
  id: '/$candidacyId',
  path: '/$candidacyId',
  getParentRoute: () => CoverLettersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cover-letters': typeof CoverLettersRouteRouteWithChildren
  '/jobs': typeof JobsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cover-letters/$candidacyId': typeof CoverLettersCandidacyIdRoute
  '/jobs/$candidacyId': typeof JobsCandidacyIdRoute
  '/onboarding/conversation': typeof OnboardingConversationRoute
  '/onboarding/criteria': typeof OnboardingCriteriaRoute
  '/onboarding/home': typeof OnboardingHomeRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/resume': typeof OnboardingResumeRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/cover-letters/': typeof CoverLettersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cover-letters/$candidacyId': typeof CoverLettersCandidacyIdRoute
  '/jobs/$candidacyId': typeof JobsCandidacyIdRoute
  '/onboarding/conversation': typeof OnboardingConversationRoute
  '/onboarding/criteria': typeof OnboardingCriteriaRoute
  '/onboarding/home': typeof OnboardingHomeRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/resume': typeof OnboardingResumeRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/cover-letters': typeof CoverLettersIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cover-letters': typeof CoverLettersRouteRouteWithChildren
  '/jobs': typeof JobsRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cover-letters/$candidacyId': typeof CoverLettersCandidacyIdRoute
  '/jobs/$candidacyId': typeof JobsCandidacyIdRoute
  '/onboarding/conversation': typeof OnboardingConversationRoute
  '/onboarding/criteria': typeof OnboardingCriteriaRoute
  '/onboarding/home': typeof OnboardingHomeRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/resume': typeof OnboardingResumeRoute
  '/onboarding/review': typeof OnboardingReviewRoute
  '/cover-letters/': typeof CoverLettersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cover-letters'
    | '/jobs'
    | '/onboarding'
    | '/auth'
    | '/cover-letters/$candidacyId'
    | '/jobs/$candidacyId'
    | '/onboarding/conversation'
    | '/onboarding/criteria'
    | '/onboarding/home'
    | '/onboarding/intro'
    | '/onboarding/resume'
    | '/onboarding/review'
    | '/cover-letters/'
    | '/jobs/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cover-letters/$candidacyId'
    | '/jobs/$candidacyId'
    | '/onboarding/conversation'
    | '/onboarding/criteria'
    | '/onboarding/home'
    | '/onboarding/intro'
    | '/onboarding/resume'
    | '/onboarding/review'
    | '/cover-letters'
    | '/jobs'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/cover-letters'
    | '/jobs'
    | '/onboarding'
    | '/auth'
    | '/cover-letters/$candidacyId'
    | '/jobs/$candidacyId'
    | '/onboarding/conversation'
    | '/onboarding/criteria'
    | '/onboarding/home'
    | '/onboarding/intro'
    | '/onboarding/resume'
    | '/onboarding/review'
    | '/cover-letters/'
    | '/jobs/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverLettersRouteRoute: typeof CoverLettersRouteRouteWithChildren
  JobsRouteRoute: typeof JobsRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letters': {
      id: '/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof CoverLettersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/cover-letters/': {
      id: '/cover-letters/'
      path: '/'
      fullPath: '/cover-letters/'
      preLoaderRoute: typeof CoverLettersIndexRouteImport
      parentRoute: typeof CoverLettersRouteRoute
    }
    '/onboarding/review': {
      id: '/onboarding/review'
      path: '/review'
      fullPath: '/onboarding/review'
      preLoaderRoute: typeof OnboardingReviewRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/resume': {
      id: '/onboarding/resume'
      path: '/resume'
      fullPath: '/onboarding/resume'
      preLoaderRoute: typeof OnboardingResumeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/intro': {
      id: '/onboarding/intro'
      path: '/intro'
      fullPath: '/onboarding/intro'
      preLoaderRoute: typeof OnboardingIntroRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/home': {
      id: '/onboarding/home'
      path: '/home'
      fullPath: '/onboarding/home'
      preLoaderRoute: typeof OnboardingHomeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/criteria': {
      id: '/onboarding/criteria'
      path: '/criteria'
      fullPath: '/onboarding/criteria'
      preLoaderRoute: typeof OnboardingCriteriaRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/conversation': {
      id: '/onboarding/conversation'
      path: '/conversation'
      fullPath: '/onboarding/conversation'
      preLoaderRoute: typeof OnboardingConversationRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/jobs/$candidacyId': {
      id: '/jobs/$candidacyId'
      path: '/$candidacyId'
      fullPath: '/jobs/$candidacyId'
      preLoaderRoute: typeof JobsCandidacyIdRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/cover-letters/$candidacyId': {
      id: '/cover-letters/$candidacyId'
      path: '/$candidacyId'
      fullPath: '/cover-letters/$candidacyId'
      preLoaderRoute: typeof CoverLettersCandidacyIdRouteImport
      parentRoute: typeof CoverLettersRouteRoute
    }
  }
}

interface CoverLettersRouteRouteChildren {
  CoverLettersCandidacyIdRoute: typeof CoverLettersCandidacyIdRoute
  CoverLettersIndexRoute: typeof CoverLettersIndexRoute
}

const CoverLettersRouteRouteChildren: CoverLettersRouteRouteChildren = {
  CoverLettersCandidacyIdRoute: CoverLettersCandidacyIdRoute,
  CoverLettersIndexRoute: CoverLettersIndexRoute,
}

const CoverLettersRouteRouteWithChildren =
  CoverLettersRouteRoute._addFileChildren(CoverLettersRouteRouteChildren)

interface JobsRouteRouteChildren {
  JobsCandidacyIdRoute: typeof JobsCandidacyIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteRouteChildren: JobsRouteRouteChildren = {
  JobsCandidacyIdRoute: JobsCandidacyIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteRouteWithChildren = JobsRouteRoute._addFileChildren(
  JobsRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingConversationRoute: typeof OnboardingConversationRoute
  OnboardingCriteriaRoute: typeof OnboardingCriteriaRoute
  OnboardingHomeRoute: typeof OnboardingHomeRoute
  OnboardingIntroRoute: typeof OnboardingIntroRoute
  OnboardingResumeRoute: typeof OnboardingResumeRoute
  OnboardingReviewRoute: typeof OnboardingReviewRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingConversationRoute: OnboardingConversationRoute,
  OnboardingCriteriaRoute: OnboardingCriteriaRoute,
  OnboardingHomeRoute: OnboardingHomeRoute,
  OnboardingIntroRoute: OnboardingIntroRoute,
  OnboardingResumeRoute: OnboardingResumeRoute,
  OnboardingReviewRoute: OnboardingReviewRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverLettersRouteRoute: CoverLettersRouteRouteWithChildren,
  JobsRouteRoute: JobsRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
