#!/usr/bin/env bash
#
# Regenerate packages/db/src/database.types.ts from the Supabase migrations by
# applying them to a throwaway Postgres and introspecting the `public` schema.
#
# This is the SINGLE source of truth used both locally (`pnpm db:gen`) and by the
# CI drift gate (`pnpm --filter @archer/db db:gen:check`), so the two can never
# diverge — a stale committed file fails CI.
#
# Usage:
#   gen-types.sh           # write the file
#   gen-types.sh --check   # regenerate to a temp file and fail if it differs
set -euo pipefail

DB_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MIGRATIONS_DIR="$DB_DIR/supabase/migrations"
BOOTSTRAP="$DB_DIR/scripts/_bootstrap.sql"
OUT="$DB_DIR/src/database.types.ts"

CONTAINER="archer-typegen-pg"
PORT="${TYPEGEN_PG_PORT:-55432}"
DB_URL="postgresql://postgres:postgres@127.0.0.1:${PORT}/postgres"

log() { printf '\033[36m[db:gen]\033[0m %s\n' "$*" >&2; }
cleanup() { docker rm -f "$CONTAINER" >/dev/null 2>&1 || true; }
trap cleanup EXIT
cleanup

log "starting ephemeral postgres:17 on :${PORT}"
docker run -d --name "$CONTAINER" -e POSTGRES_PASSWORD=postgres \
  -p "${PORT}:5432" postgres:17 >/dev/null

log "waiting for postgres to accept connections"
for _ in $(seq 1 60); do
  docker exec "$CONTAINER" pg_isready -U postgres -q && break
  sleep 1
done

log "applying auth stub + migrations"
docker exec -i "$CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d postgres < "$BOOTSTRAP" >/dev/null
for f in "$MIGRATIONS_DIR"/*.sql; do
  log "  -> $(basename "$f")"
  docker exec -i "$CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d postgres < "$f" >/dev/null
done

log "generating TypeScript types (supabase gen types)"
GENERATED="$(npx --yes supabase@latest gen types typescript --db-url "$DB_URL" --schema public)"

HEADER="// AUTO-GENERATED by packages/db/scripts/gen-types.sh — DO NOT EDIT BY HAND.
// Regenerate with \`pnpm db:gen\`. The CI drift gate fails if this is stale.
"

if [[ "${1:-}" == "--check" ]]; then
  TMP="$(mktemp)"
  printf '%s\n%s\n' "$HEADER" "$GENERATED" > "$TMP"
  if diff -u "$OUT" "$TMP" >&2; then
    log "✓ database.types.ts is in sync with the migrations"
  else
    log "✖ database.types.ts is STALE — run 'pnpm db:gen' and commit the result."
    exit 1
  fi
else
  printf '%s\n%s\n' "$HEADER" "$GENERATED" > "$OUT"
  log "✓ wrote $OUT"
fi
